# Generated by Django 5.1.4 on 2024-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
