# Generated by Django 5.1.4 on 2024-12-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0003_seller_productsize_seller_name_productsize_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='saleshistory',
            options={'ordering': ['-sold_date']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-date_registered']},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='seller_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
