# Generated by Django 5.1.4 on 2025-01-30 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0004_alter_group_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, related_name='groups_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='high_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
