# Generated by Django 5.1.4 on 2025-02-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0006_alter_group_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
