# Generated by Django 5.1.4 on 2025-02-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0007_alter_product_options_alter_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
