# Generated by Django 5.1.4 on 2025-02-11 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0008_remove_productsize_seller_name_seller_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
