# Generated by Django 5.1.4 on 2025-02-11 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0010_rename_saleshistory_historyitem_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='owner',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='richman.seller'),
            preserve_default=False,
        ),
    ]
