# Generated by Django 5.1.4 on 2025-02-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0011_remove_historyitem_owner_historyitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='richman.seller'),
        ),
    ]
