# Generated by Django 5.1.4 on 2025-02-11 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0012_alter_historyitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='richman.history'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='richman.seller'),
            preserve_default=False,
        ),
    ]
