# Generated by Django 5.1.4 on 2025-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0014_alter_historyitem_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='seller',
        ),
    ]
