# Generated by Django 5.1.4 on 2025-02-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0015_remove_historyitem_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-group_date']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group_date',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('owner', 'group_date')},
        ),
    ]
