# Generated by Django 5.1.4 on 2025-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0016_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
    ]
