# Generated by Django 5.1.4 on 2025-02-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0018_group_unique_owner_group_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_owner_group_date',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('owner', 'group_date')},
        ),
    ]
